server:
  port: 80
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.78.172.165:3306/sohome?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    minIdle: 1
    maxActive: 2
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'ZTM' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  mvc:
    throw-exception-if-no-handler-found: true
  aop:
    auto: true
  resources:
    static-locations: classpath:/static/
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .html
    request-context-attribute: request
    charset: UTF-8
    cache: false
    settings: 
      template_update_delay: 0
    
#日志
